### ISSUE TITLE
Found unknown file, ignoring

### ISSUE THREAD

**Issue by jas-deep** [square/keysync#75]
I am facing an issue while using keywhiz and keysync client. I could store the secrets in keywhiz however keysync client is not fetching my secret file. I see warning in keysync logs which say "Found unknown file, ignoring"

What could be the issue?

**Comment by mcpherrinm** [comment]
> Found unknown file, ignoring
This message occurs when there's a file in the SecretsDir.  Normally there are no files in that directory, as keysync puts a directory for each client, with the secrets in each directory.

Are your secrets assigned to the right client?  Secrets and clients need to both be in a group for keysync to fetch them.

Do your client certs have a CN matching the client name?  The client cert is how Keywhiz identifies which client is connecting.
